import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.45.0';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

type CouponExpiryCandidate = {
  id: string;
  expiry: string | null;
};

function buildUtcEndOfDay(year: number, month: number, day: number): Date | null {
  const parsed = new Date(Date.UTC(year, month - 1, day, 23, 59, 59, 999));

  if (
    Number.isNaN(parsed.getTime()) ||
    parsed.getUTCFullYear() !== year ||
    parsed.getUTCMonth() !== month - 1 ||
    parsed.getUTCDate() !== day
  ) {
    return null;
  }

  return parsed;
}

function parseExpiryDate(expiry: string | null): Date | null {
  if (!expiry) return null;

  const normalized = expiry.trim();
  if (!normalized) return null;

  // Accept the formats generated by sync providers/admin forms and ignore labels
  // such as "Sem validade" to avoid disabling valid coupons by accident.
  const isoDateMatch = normalized.match(/^(\d{4})-(\d{2})-(\d{2})(?:[T ].*)?$/);
  if (isoDateMatch) {
    const [, year, month, day] = isoDateMatch;
    return buildUtcEndOfDay(Number(year), Number(month), Number(day));
  }

  const brDateMatch = normalized.match(/^(\d{2})\/(\d{2})\/(\d{4})$/);
  if (brDateMatch) {
    const [, day, month, year] = brDateMatch;
    return buildUtcEndOfDay(Number(year), Number(month), Number(day));
  }

  return null;
}

serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response(null, { headers: corsHeaders });

  const supabase = createClient(
    Deno.env.get('SUPABASE_URL')!,
    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
  );

  try {
    console.log('[expire-coupons] Iniciando rotina segura de desativação de cupons vencidos...');

    const now = new Date();

    const { data: candidates, error: selectError } = await supabase
      .from('coupons')
      .select('id, expiry')
      .eq('status', true)
      .not('expiry', 'is', null)
      .neq('expiry', '');

    if (selectError) throw selectError;

    const parsedCandidates = ((candidates ?? []) as CouponExpiryCandidate[]).map((coupon) => ({
      ...coupon,
      expiryDate: parseExpiryDate(coupon.expiry),
    }));

    const expiredIds = parsedCandidates
      .filter((coupon) => coupon.expiryDate !== null && coupon.expiryDate < now)
      .map((coupon) => coupon.id);

    const ignoredInvalidExpiryCount = parsedCandidates.filter((coupon) => coupon.expiryDate === null).length;

    if (expiredIds.length === 0) {
      console.log('[expire-coupons] Nenhum cupom vencido encontrado para desativar.');

      return new Response(
        JSON.stringify({ success: true, disabled_count: 0, ignored_invalid_expiry_count: ignoredInvalidExpiryCount }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const { data, error: updateError } = await supabase
      .from('coupons')
      .update({ status: false })
      .in('id', expiredIds)
      .select('id');

    if (updateError) throw updateError;

    console.log(`[expire-coupons] ${data?.length ?? 0} cupons vencidos desativados sem exclusão.`);

    return new Response(
      JSON.stringify({
        success: true,
        disabled_count: data?.length ?? 0,
        ignored_invalid_expiry_count: ignoredInvalidExpiryCount,
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : 'Erro desconhecido';

    console.error('[expire-coupons] Erro:', message);
    return new Response(
      JSON.stringify({ error: message }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
