/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as DescontoSlugRouteImport } from './routes/desconto.$slug'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'

const IndexRoute = IndexRouteImport.update({
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const AdminLoginRoute = AdminLoginRouteImport.update({
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

const BlogSlugRoute = BlogSlugRouteImport.update({
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

const DescontoSlugRoute = DescontoSlugRouteImport.update({
  path: '/desconto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

const AdminIndexRoute = AdminIndexRouteImport.update({
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)

const BlogIndexRoute = BlogIndexRouteImport.update({
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/desconto/$slug': typeof DescontoSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/desconto/$slug': typeof DescontoSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/desconto/$slug': typeof DescontoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin/login' | '/blog/$slug' | '/desconto/$slug' | '/admin' | '/blog'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin/login' | '/blog/$slug' | '/desconto/$slug' | '/admin' | '/blog'
  id: '__root__' | '/' | '/admin/login' | '/blog/$slug' | '/desconto/$slug' | '/admin/' | '/blog/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLoginRoute: typeof AdminLoginRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DescontoSlugRoute: typeof DescontoSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desconto/$slug': {
      id: '/desconto/$slug'
      path: '/desconto/$slug'
      fullPath: '/desconto/$slug'
      preLoaderRoute: typeof DescontoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

export const routeTree = rootRouteImport._addFileChildren({
  IndexRoute,
  AdminLoginRoute,
  BlogSlugRoute,
  DescontoSlugRoute,
  AdminIndexRoute,
  BlogIndexRoute,
})