/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as AdminLoginImport } from './routes/admin/login'
import { Route as BlogIndexImport } from './routes/blog/index'
import { Route as BlogSlugImport } from './routes/blog/$slug'
import { Route as DescontoSlugImport } from './routes/desconto/$slug'

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)

const AdminLoginRoute = AdminLoginImport.update({
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

const BlogIndexRoute = BlogIndexImport.update({
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)

const BlogSlugRoute = BlogSlugImport.update({
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

const DescontoSlugRoute = DescontoSlugImport.update({
  path: '/desconto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugImport
      parentRoute: typeof rootRouteImport
    }
    '/desconto/$slug': {
      id: '/desconto/$slug'
      path: '/desconto/$slug'
      fullPath: '/desconto/$slug'
      preLoaderRoute: typeof DescontoSlugImport
      parentRoute: typeof rootRouteImport
    }
  }
}

export const routeTree = rootRouteImport._addFileChildren([
  IndexRoute,
  AdminIndexRoute,
  AdminLoginRoute,
  BlogIndexRoute,
  BlogSlugRoute,
  DescontoSlugRoute,
])