/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as PerguntasFrequentesRouteImport } from './routes/perguntas-frequentes'
import { Route as LojasRouteImport } from './routes/lojas'
import { Route as FaleConoscoRouteImport } from './routes/fale-conosco'
import { Route as CuponsRouteImport } from './routes/cupons'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminblogRouteImport } from './routes/adminblog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DescontoSlugRouteImport } from './routes/desconto.$slug'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminAccessDeniedRouteImport } from './routes/admin.access-denied'

const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const PerguntasFrequentesRoute = PerguntasFrequentesRouteImport.update({
  id: '/perguntas-frequentes',
  path: '/perguntas-frequentes',
  getParentRoute: () => rootRouteImport,
} as any)
const LojasRoute = LojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/lojas.lazy').then((d) => d.Route))
const FaleConoscoRoute = FaleConoscoRouteImport.update({
  id: '/fale-conosco',
  path: '/fale-conosco',
  getParentRoute: () => rootRouteImport,
} as any)
const CuponsRoute = CuponsRouteImport.update({
  id: '/cupons',
  path: '/cupons',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/cupons.lazy').then((d) => d.Route))
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminblogRoute = AdminblogRouteImport.update({
  id: '/adminblog',
  path: '/adminblog',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/adminblog.lazy').then((d) => d.Route))
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any).lazy(() => import('./routes/blog.index.lazy').then((d) => d.Route))
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin.index.lazy').then((d) => d.Route))
const DescontoSlugRoute = DescontoSlugRouteImport.update({
  id: '/desconto/$slug',
  path: '/desconto/$slug',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/desconto.$slug.lazy').then((d) => d.Route),
)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/categoria.$slug.lazy').then((d) => d.Route),
)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any).lazy(() => import('./routes/blog.$slug.lazy').then((d) => d.Route))
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin.login.lazy').then((d) => d.Route))
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin.coupons.lazy').then((d) => d.Route))
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin.blog.lazy').then((d) => d.Route))
const AdminAccessDeniedRoute = AdminAccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.access-denied.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/adminblog': typeof AdminblogRoute
  '/blog': typeof BlogRouteWithChildren
  '/como-funciona': typeof ComoFuncionaRoute
  '/cupons': typeof CuponsRoute
  '/fale-conosco': typeof FaleConoscoRoute
  '/lojas': typeof LojasRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/quem-somos': typeof QuemSomosRoute
  '/admin/access-denied': typeof AdminAccessDeniedRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/desconto/$slug': typeof DescontoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adminblog': typeof AdminblogRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/cupons': typeof CuponsRoute
  '/fale-conosco': typeof FaleConoscoRoute
  '/lojas': typeof LojasRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/quem-somos': typeof QuemSomosRoute
  '/admin/access-denied': typeof AdminAccessDeniedRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/desconto/$slug': typeof DescontoSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/adminblog': typeof AdminblogRoute
  '/blog': typeof BlogRouteWithChildren
  '/como-funciona': typeof ComoFuncionaRoute
  '/cupons': typeof CuponsRoute
  '/fale-conosco': typeof FaleConoscoRoute
  '/lojas': typeof LojasRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/quem-somos': typeof QuemSomosRoute
  '/admin/access-denied': typeof AdminAccessDeniedRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/desconto/$slug': typeof DescontoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/adminblog'
    | '/blog'
    | '/como-funciona'
    | '/cupons'
    | '/fale-conosco'
    | '/lojas'
    | '/perguntas-frequentes'
    | '/quem-somos'
    | '/admin/access-denied'
    | '/admin/blog'
    | '/admin/coupons'
    | '/admin/login'
    | '/blog/$slug'
    | '/categoria/$slug'
    | '/desconto/$slug'
    | '/admin/'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adminblog'
    | '/como-funciona'
    | '/cupons'
    | '/fale-conosco'
    | '/lojas'
    | '/perguntas-frequentes'
    | '/quem-somos'
    | '/admin/access-denied'
    | '/admin/blog'
    | '/admin/coupons'
    | '/admin/login'
    | '/blog/$slug'
    | '/categoria/$slug'
    | '/desconto/$slug'
    | '/admin'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/adminblog'
    | '/blog'
    | '/como-funciona'
    | '/cupons'
    | '/fale-conosco'
    | '/lojas'
    | '/perguntas-frequentes'
    | '/quem-somos'
    | '/admin/access-denied'
    | '/admin/blog'
    | '/admin/coupons'
    | '/admin/login'
    | '/blog/$slug'
    | '/categoria/$slug'
    | '/desconto/$slug'
    | '/admin/'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminblogRoute: typeof AdminblogRoute
  BlogRoute: typeof BlogRouteWithChildren
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  CuponsRoute: typeof CuponsRoute
  FaleConoscoRoute: typeof FaleConoscoRoute
  LojasRoute: typeof LojasRoute
  PerguntasFrequentesRoute: typeof PerguntasFrequentesRoute
  QuemSomosRoute: typeof QuemSomosRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  DescontoSlugRoute: typeof DescontoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perguntas-frequentes': {
      id: '/perguntas-frequentes'
      path: '/perguntas-frequentes'
      fullPath: '/perguntas-frequentes'
      preLoaderRoute: typeof PerguntasFrequentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lojas': {
      id: '/lojas'
      path: '/lojas'
      fullPath: '/lojas'
      preLoaderRoute: typeof LojasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fale-conosco': {
      id: '/fale-conosco'
      path: '/fale-conosco'
      fullPath: '/fale-conosco'
      preLoaderRoute: typeof FaleConoscoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cupons': {
      id: '/cupons'
      path: '/cupons'
      fullPath: '/cupons'
      preLoaderRoute: typeof CuponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminblog': {
      id: '/adminblog'
      path: '/adminblog'
      fullPath: '/adminblog'
      preLoaderRoute: typeof AdminblogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/desconto/$slug': {
      id: '/desconto/$slug'
      path: '/desconto/$slug'
      fullPath: '/desconto/$slug'
      preLoaderRoute: typeof DescontoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/access-denied': {
      id: '/admin/access-denied'
      path: '/access-denied'
      fullPath: '/admin/access-denied'
      preLoaderRoute: typeof AdminAccessDeniedRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAccessDeniedRoute: typeof AdminAccessDeniedRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccessDeniedRoute: AdminAccessDeniedRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminblogRoute: AdminblogRoute,
  BlogRoute: BlogRouteWithChildren,
  ComoFuncionaRoute: ComoFuncionaRoute,
  CuponsRoute: CuponsRoute,
  FaleConoscoRoute: FaleConoscoRoute,
  LojasRoute: LojasRoute,
  PerguntasFrequentesRoute: PerguntasFrequentesRoute,
  QuemSomosRoute: QuemSomosRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  DescontoSlugRoute: DescontoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
